apiVersion: apps/v1 
kind: Deployment
metadata:
  name: portfolio-react
  labels:
    app: react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      contaniers:
      - name: react-app
        image: amerab/portfolio
        ports:
        - containerPort: 3000